
language: python
python:
  - 3.5
  - 3.6

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install axelrod
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  # Build the documentation
  - cd docs; make html
  # Run the test suit with coverage
  - cd ..
  # Run the doctests
  - python -m unittest test_utils
